import { useState } from 'react'
import { Button } from '../components/ui/Button'
import { createTrip } from '../services/tripStorage'
import { formatDuration, formatTripDate, getTripDuration, isDateRangeValid } from '../utils/date'

type FormValues = { destination: string; startDate: string; endDate: string }
type Errors = Partial<Record<keyof FormValues | 'storage', string>>
const initialValues: FormValues = { destination: '', startDate: '', endDate: '' }

export function CreateTrip({ onBack, onCreated }: { onBack: () => void; onCreated: () => void }) {
  const [step, setStep] = useState<1 | 2>(1); const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState<Errors>({}); const [saving, setSaving] = useState(false)
  const duration = values.startDate && values.endDate && isDateRangeValid(values.startDate, values.endDate) ? getTripDuration(values.startDate, values.endDate) : null
  const update = (field: keyof FormValues, value: string) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined, storage: undefined })) }
  const validate = () => { const next: Errors = {}; if (!values.destination.trim()) next.destination = 'Please enter a destination.'; if (!values.startDate) next.startDate = 'Please select a start date.'; if (!values.endDate) next.endDate = 'Please select an end date.'; if (values.startDate && values.endDate && !isDateRangeValid(values.startDate, values.endDate)) next.endDate = 'Your end date must be on or after your start date.'; setErrors(next); return !Object.keys(next).length }
  const continueToReview = (event: React.FormEvent) => { event.preventDefault(); if (validate()) { setValues((current) => ({ ...current, destination: current.destination.trim() })); setStep(2) } }
  const save = () => { setSaving(true); try { createTrip({ ...values, destination: values.destination.trim() }); onCreated() } catch (error) { setErrors({ storage: error instanceof Error ? error.message : 'We could not save this trip. Please try again.' }); setSaving(false) } }
  return <main className="create-trip-page" id="main-content"><button className="back-link" type="button" onClick={onBack}>← Back to dashboard</button><div className="create-trip-layout"><header className="create-trip-header"><p className="eyebrow">PLAN YOUR NEXT ADVENTURE</p><h1>Create a new trip</h1><p>Tell us where and when you&apos;re travelling.</p></header><section className="trip-form-card" aria-labelledby="form-heading"><div className="progress"><span className={step === 1 ? 'is-current' : 'is-complete'}>1 <b>Trip details</b></span><i /><span className={step === 2 ? 'is-current' : ''}>2 <b>Review &amp; create</b></span></div>{step === 1 ? <form onSubmit={continueToReview} noValidate><div className="form-heading"><p>STEP 1 OF 2</p><h2 id="form-heading">Trip details</h2><span>Start with the essentials. You can review everything before creating your trip.</span></div><div className="form-fields"><label>Destination<input value={values.destination} onChange={(event) => update('destination', event.target.value)} placeholder="e.g. Goa, India" aria-invalid={Boolean(errors.destination)} aria-describedby={errors.destination ? 'destination-error' : undefined} /></label>{errors.destination && <p className="field-error" id="destination-error">{errors.destination}</p>}<div className="date-fields"><label>Start date<input type="date" value={values.startDate} onChange={(event) => update('startDate', event.target.value)} aria-invalid={Boolean(errors.startDate)} /></label><label>End date<input type="date" value={values.endDate} min={values.startDate || undefined} onChange={(event) => update('endDate', event.target.value)} aria-invalid={Boolean(errors.endDate)} /></label></div>{(errors.startDate || errors.endDate) && <p className="field-error">{errors.startDate || errors.endDate}</p>}{duration && <div className="duration-preview"><span>✦</span><div><strong>{formatDuration(duration)}</strong><p>{formatTripDate(values.startDate)} → {formatTripDate(values.endDate)}</p></div></div>}</div><div className="form-actions"><Button type="submit">Continue to review <span aria-hidden="true">→</span></Button></div></form> : <div><div className="form-heading"><p>STEP 2 OF 2</p><h2 id="form-heading">Review your trip</h2><span>Everything looks good. Create your trip when you&apos;re ready.</span></div><dl className="review-list"><div><dt>Destination</dt><dd>{values.destination}</dd></div><div><dt>Start date</dt><dd>{formatTripDate(values.startDate)}</dd></div><div><dt>End date</dt><dd>{formatTripDate(values.endDate)}</dd></div><div><dt>Duration</dt><dd>{duration && formatDuration(duration)}</dd></div></dl>{errors.storage && <p className="field-error" role="alert">{errors.storage}</p>}<div className="form-actions review-actions"><Button variant="secondary" onClick={() => setStep(1)}>Back</Button><Button onClick={save} disabled={saving}>{saving ? 'Creating trip…' : 'Create trip'}</Button></div></div>}</section></div></main>
}
