import './styles.css';import {layout} from './components/layout/AppLayout';import{el,button,card,emptyState,skeleton}from'./components/ui';import{tripsApi}from'./api/trips.api';import{membersApi}from'./api/members.api';import{expensesApi}from'./api/expenses.api';import{settlementsApi}from'./api/settlements.api';import{categories}from'./lib/calculations';import{formatCurrency,formatRange,formatDate,tripDuration,initials}from'./utils/format';import{ExpenseCategory,Member,Trip}from'./types';import{locationsApi}from'./api/locations.api';
const app=document.querySelector('#app')!;let toastTimer:any;function toast(m:string){clearTimeout(toastTimer);document.body.append(el('div',{class:'toast',role:'status'},m));toastTimer=setTimeout(()=>document.querySelector('.toast')?.remove(),2200)}
async function mount(node:HTMLElement|Promise<HTMLElement>){app.innerHTML='';app.append(layout(node instanceof Promise?skeleton():node));if(node instanceof Promise){const n=await node;app.innerHTML='';app.append(layout(n));}}
function notFound(){return emptyState('Something went wrong.','We could not find that page or trip.',button('Back to Trips','secondary',()=>go('/trips')))}function go(p:string){history.pushState(null,'',p);route()}
function tripCard(t:Trip,summary:any,members:Member[]){return card(el('div',{class:'row'},el('div',{},el('div',{class:'eyebrow'},t.status),el('h3',{},`${t.destination} trip`)),el('span',{class:'pill'},`${members.length} members`)),el('p',{class:'muted'},formatRange(t)),el('div',{class:'row'},el('b',{},`${formatCurrency(summary.totalSpent)} spent`),el('span',{class:'muted'},`${formatCurrency(summary.perPerson,true)} / person`)),button('View Trip →','secondary',()=>go(`/trips/${t.id}`)))}
async function dashboard(){const ts=await tripsApi.list();if(!ts.length)return emptyState('Your adventures start here.','Create your first trip and let TripC handle the math.',button('Start your first trip','primary',()=>go('/trips/new')));const enriched=await Promise.all(ts.map(async t=>({t,m:await membersApi.list(t.id),s:await settlementsApi.summary(t.id)})));return el('div',{class:'stack'},el('section',{class:'hero'},el('div',{class:'panel'},el('div',{class:'eyebrow'},'Welcome back 👋'),el('h1',{class:'h1'},'Ready to plan your next adventure?'),el('p',{class:'lead'},'TripC turns shared trip spending into clear balances, simple settlements, and zero spreadsheet stress.'),button('START A TRIP','primary',()=>go('/trips/new'))),card(el('span',{class:'eyebrow'},'Quick read'),el('h2',{},formatCurrency(enriched.reduce((a,x)=>a+x.s.totalSpent,0))),el('p',{class:'muted'},'tracked across active and completed trips'))),el('h2',{},'Active trips'),el('div',{class:'grid two'},...enriched.filter(x=>x.t.status==='active').map(x=>tripCard(x.t,x.s,x.m))),el('h2',{},'Recent / completed trips'),el('div',{class:'grid three'},...enriched.filter(x=>x.t.status==='completed').map(x=>tripCard(x.t,x.s,x.m))))}
function field(label:string,input:HTMLElement,err=''){return el('label',{class:'field'},el('span',{},label),input,el('span',{class:'error'},err))}
function createTrip(){let step=1,dest='Goa',country='India',start='2026-09-15',end='2026-09-20',names=['Shubham','Rahul'];const root=el('div');const render=()=>{root.innerHTML='';root.append(el('div',{class:'panel stack'},el('div',{class:'stepper'},...['Trip Details','Members','Ready'].map((s,i)=>el('div',{class:`step ${step===i+1?'on':''}`},`0${i+1} ${s}`))), step===1?el('form',{class:'stack',onSubmit:(e:Event)=>{e.preventDefault();if(new Date(end)<new Date(start))return alert('End date cannot be before start date.');step=2;render()}},el('h1',{},'Where are you going?'),field('Destination search',Object.assign(el('input',{value:`${dest}, ${country}`,placeholder:'Goa, India','aria-label':'Destination'}),{oninput:async(ev:any)=>{const r=await locationsApi.search(ev.target.value);const v=r[0];if(v){dest=v.city;country=v.country}}})),el('div',{class:'grid two'},field('Start date',Object.assign(el('input',{type:'date',value:start}),{oninput:(e:any)=>start=e.target.value})),field('End date',Object.assign(el('input',{type:'date',value:end}),{oninput:(e:any)=>end=e.target.value}))),el('p',{class:'pill'},tripDuration(start,end)),button('CONTINUE','primary')):step===2?el('div',{class:'stack'},el('h1',{},`Who's going?`),...names.map((n,i)=>el('div',{class:'card row'},el('div',{class:'row'},el('div',{class:'avatar'},initials(n)),el('input',{value:n,'aria-label':`Member ${i+1}`,onInput:(e:any)=>names[i]=e.target.value}),i===0?el('span',{class:'pill'},'Creator'):''),i>0?button('Remove','danger',()=>{if(confirm(`Remove ${n}?`)){names.splice(i,1);render()}}):'')),button('+ Add member','secondary',()=>{names.push(`Member ${names.length+1}`);render()}),el('div',{class:'row'},button('Back','ghost',()=>{step=1;render()}),button('Review trip','primary',()=>{if(new Set(names.map(n=>n.trim().toLowerCase())).size!==names.length)return alert('Member names must be unique.');step=3;render()}))):el('div',{class:'stack'},el('h1',{},'Ready to create your trip'),el('p',{class:'muted'},`${dest}, ${country} · ${tripDuration(start,end)} · ${names.length} members`),button('Create trip','primary',async()=>{const t=await tripsApi.create({destination:dest,country,startDate:start,endDate:end,memberNames:names});toast('Trip created successfully.');go(`/trips/${t.id}`)}))))};render();return root}
async function tripPage(id:string,tab='dashboard'){const [t,m,ex,s]=await Promise.all([tripsApi.get(id),membersApi.list(id),expensesApi.list(id),settlementsApi.summary(id)]);if(!t)return notFound();const name=(mid:string)=>m.find(x=>x.id===mid)?.name||'Someone';const bars=Object.entries(s.categoryTotals).filter(([,v])=>v>0);const head=el('div',{class:'stack'},el('a',{href:'/trips',onClick:(e:Event)=>{e.preventDefault();go('/trips')}},'← Trips'),el('div',{class:'row'},el('div',{},el('h1',{class:'h1'},t.destination),el('p',{class:'muted'},`${formatRange(t)} · ${m.length} members`)),el('div',{class:'row'},button('Manage members','secondary',()=>go(`/trips/${id}/members`)),button('Expenses','secondary',()=>go(`/trips/${id}/expenses`)),button('Summary','secondary',()=>go(`/trips/${id}/summary`)))));
if(tab==='members')return el('div',{class:'stack'},head,card(el('h2',{},'Manage members'),...m.map(x=>el('div',{class:'row'},el('span',{},`${x.name} ${x.isCreator?'· Creator':''}`),!x.isCreator?button('Remove','danger',async()=>{await membersApi.delete(id,x.id);toast('Member removed.');route()}):'')),button('+ Add member','primary',async()=>{const n=prompt('Member name');if(n){await membersApi.create(id,n);toast('Member added.');route()}})));
if(tab==='expenses')return expensesPage(id,m,ex,name);
const summaryBlocks=el('div',{class:'grid four'},
 card(el('span',{class:'muted'},'Total spent'),el('b',{},formatCurrency(s.totalSpent))),
 card(el('span',{class:'muted'},'Per person'),el('b',{},formatCurrency(s.perPerson,true))),
 card(el('span',{class:'muted'},'Expenses'),el('b',{},String(s.expenseCount))),
 card(el('span',{class:'muted'},'Unsettled'),el('b',{},formatCurrency(s.unsettledTotal))));
const settlement=card(el('h2',{},tab==='summary'?'Final settlement':'Who owes whom'),...(s.settlements.length?s.settlements.map(x=>el('div',{class:'card row'},el('b',{},name(x.fromMemberId)),el('span',{class:'muted'},'owes'),el('b',{},formatCurrency(x.amount)),el('span',{class:'muted'},'to'),el('b',{},name(x.toMemberId)))):[el('p',{class:'muted'},'Everyone is settled.')]));
const cats=card(el('h2',{},'Spending by category'),...bars.map(([c,v])=>el('div',{},el('div',{class:'row'},el('span',{},c),el('b',{},formatCurrency(v as number))),el('div',{class:'bar'},el('i',{style:`width:${((v as number)/s.totalSpent)*100}%`})))));
const balances=card(el('h2',{},'Member balances'),...s.memberBalances.map(b=>el('div',{class:'row'},el('span',{},name(b.memberId)),el('b',{class:b.balance>0?'positive':b.balance<0?'negative':'zero'},`${b.balance>0?'Receives ':b.balance<0?'Pays ':'Settled '}${formatCurrency(Math.abs(b.balance),true)}`))));
return el('div',{class:'stack'},head,summaryBlocks,el('div',{class:'grid two'},settlement,cats),balances,tab==='summary'?button('COMPLETE TRIP','primary',async()=>{if(confirm('Is your trip completed?\n\nCompleting this trip will move it to your completed trips.')){await tripsApi.complete(id);toast('🎉 Trip completed! Your trip summary is ready.');route()}}):'')}
function expensesPage(id:string,m:Member[],ex:any[],name:(id:string)=>string){let cat='All',sort='new';const root=el('div',{class:'stack'});const render=()=>{const list=ex.filter(e=>cat==='All'||e.category===cat).sort((a,b)=>sort==='high'?b.amount-a.amount:sort==='low'?a.amount-b.amount:sort==='old'?+new Date(a.date)-+new Date(b.date):+new Date(b.date)-+new Date(a.date));root.innerHTML='';root.append(
 el('div',{class:'row'},el('h1',{},'Expenses'),button('+ Add expense','primary',()=>addExpense(id,m))),
 el('div',{class:'grid three'},field('Category',Object.assign(el('select',{},...['All',...categories].map(c=>el('option',{},c))),{onchange:(e:any)=>{cat=e.target.value;render()}})),field('Member',el('select',{},el('option',{},'All'),...m.map(x=>el('option',{},x.name)))),field('Sort',Object.assign(el('select',{},...['new','old','high','low'].map(x=>el('option',{value:x},x))),{onchange:(e:any)=>{sort=e.target.value;render()}}))),
 ...list.map(e=>card(el('div',{class:'expense'},el('div',{},el('h3',{},`${icon(e.category)} ${e.title}`),el('p',{class:'muted'},`${e.category} · Paid by ${name(e.paidBy)} · ${formatDate(e.date)}`)),el('div',{class:'stack'},el('b',{},formatCurrency(e.amount)),button('Delete','danger',async()=>{await expensesApi.delete(id,e.id);toast('Expense deleted.');route()})))))
)};render();return root}
function icon(c:ExpenseCategory){return {'Travelling':'🚗','Tickets':'🎟️','Food':'🍔','Activities':'🎯','Hotel':'🏨','Shopping':'🛍️','Other':'•••'}[c]}
function addExpense(id:string,m:Member[]){let amount=400,paid=m[0].id,cat:ExpenseCategory='Food';const modal=el('div',{class:'modal',role:'dialog','aria-modal':'true'},el('form',{class:'dialog stack',onSubmit:async(e:Event)=>{e.preventDefault();await expensesApi.create(id,{title:(document.querySelector('#title')as HTMLInputElement).value||'Untitled expense',amount,category:cat,paidBy:paid,date:(document.querySelector('#date')as HTMLInputElement).value,splitMemberIds:m.map(x=>x.id)});modal.remove();toast('Expense added successfully.');route()}},el('h2',{},'Add expense'),field('Title',el('input',{id:'title',required:true,placeholder:'Dinner'})),field('Amount (₹)',Object.assign(el('input',{type:'number',min:'1',value:amount}),{oninput:(e:any)=>amount=+e.target.value})),field('Category',Object.assign(el('select',{},...categories.map(c=>el('option',{},c))),{onchange:(e:any)=>cat=e.target.value})),field('Paid by',Object.assign(el('select',{},...m.map(x=>el('option',{value:x.id},x.name))),{onchange:(e:any)=>paid=e.target.value})),field('Date',el('input',{id:'date',type:'date',value:new Date().toISOString().slice(0,10)})),el('div',{class:'card'},el('b',{},'Split equally'),el('p',{class:'muted'},`${formatCurrency(amount)} total ÷ ${m.length} people = ${formatCurrency(amount/m.length,true)} each. Payer receives ${formatCurrency(amount-(amount/m.length),true)}.`)),el('div',{class:'row'},button('Cancel','ghost',()=>modal.remove()),button('Save expense','primary'))));document.body.append(modal)}
function route(){const p=location.pathname;if(p==='/')return mount(dashboard());if(p==='/trips')return mount(dashboard());if(p==='/trips/new')return mount(createTrip());const m=p.match(/^\/trips\/([^/]+)(?:\/(members|expenses|summary))?$/);return mount(m?tripPage(m[1],m[2]||'dashboard'):notFound())}addEventListener('popstate',route);document.addEventListener('click',e=>{const a=(e.target as HTMLElement).closest('a');if(a?.getAttribute('href')?.startsWith('/')){e.preventDefault();go(a.getAttribute('href')!)}});route();
